{
    'name': 'Office Management',
    'version': '1.0',
    'category': 'Custom',
    'summary': 'Manage Office Departments, Employees, Projects, Tasks and Assets',
    'depends': ['base','purchase','stock','sale'],
    'data': [
        'security/ir.model.access.csv',
        'security/user_concern_rules.xml',
        'security/user_groups.xml',
        'views/office_actions.xml',
        'views/office_menus.xml',
        'views/department_views.xml',
        'views/employee_views.xml',
        'views/project_views.xml',
        'views/task_views.xml',
        'views/asset_views.xml',
        'views/purchase_screen.xml',
        'views/quontity.xml',
        'views/sale_order.xml',
        'views/user_concern_views.xml',
        'views/user_login_menus.xml',
        'views/purchase_order.xml',
        'views/user_menus.xml',
    ],
    'installable': True,
    'application': True,
}